#!/usr/bin/env python3
"""Generate the C++ API catalog from the inventory.

The catalog is what the API registry, the dispatcher and the argument
validators read at runtime. It exists so that a member's parameters, the
permission its namespace needs, the contexts it may be called from and its
manifest-version bounds are stated once, by the upstream schemas, rather than
retyped by hand in several hundred places.

    docs/extensions/data/api-inventory.json  ->  src/extensions/generated/

The generated code contains no behaviour: it is tables. Handwritten behaviour
lives in src/extensions/api/ and reaches these tables only through the registry,
which is what keeps the two from drifting into a coupling.

Usage:
    tools/webext/codegen.py [--data DIR] [--out DIR] [--check]

--check reports whether the committed output matches what the inventory implies,
so a refreshed inventory cannot leave stale generated code behind.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs" / "extensions"
GENERATED = ROOT / "src" / "extensions" / "generated"

BANNER = """// Generated by tools/webext/codegen.py from docs/extensions/data/api-inventory.json.
// Do not edit: regenerate with `tools/webext/codegen.py`.
//
// This file is data, not behaviour. It states what the WebExtensions
// specification defines for each namespace and member, so the registry, the
// dispatcher and the argument validators all agree, and so no member is
// re-declared by hand anywhere else in the tree.
"""

# Namespaces that exist in the Gecko schemas for privileged or Mozilla-internal
# reasons. They stay in the inventory so the coverage document stays complete,
# but a registry must not offer them to an extension.
INTERNAL_NAMESPACES = {
    "activityLog", "telemetry", "geckoProfiler", "trial", "trial.ml",
    "experiments", "test", "networkStatus",
}

HEADER = BANNER + """
#pragma once

#include <cstdint>
#include <string_view>

namespace iridium::extensions::generated {

// A bitmask of the execution contexts a namespace may be reached from. The
// specification expresses this as allowedContexts on a namespace, and
// "content" and "devtools" are the only two values it ever uses, so the mapping
// is direct: a namespace that names neither is reachable everywhere.
enum ContextFlag : std::uint32_t {
    ContextNone          = 0,
    ContextBackground    = 1u << 0,  // MV2 background page or MV3 service worker
    ContextExtensionPage = 1u << 1,  // popup, options, sidebar, any extension URL
    ContextContentScript = 1u << 2,  // gecko "content"
    ContextDevTools      = 1u << 3,  // gecko "devtools"
    ContextSandboxed     = 1u << 4,  // sandboxed extension page
};

// Every context an extension-owned page or worker can be.
constexpr ContextFlag ContextAll = static_cast<ContextFlag>(
    ContextBackground | ContextExtensionPage | ContextSandboxed);

// Every context including the two an extension's own content scripts and
// devtools pages add.
constexpr ContextFlag ContextEvery = static_cast<ContextFlag>(
    ContextAll | ContextContentScript | ContextDevTools);

constexpr ContextFlag operator&(ContextFlag a, ContextFlag b)
{
    return static_cast<ContextFlag>(static_cast<std::uint32_t>(a)
        & static_cast<std::uint32_t>(b));
}

constexpr ContextFlag& operator&=(ContextFlag& a, ContextFlag b)
{
    a = a & b;
    return a;
}

enum class MemberKind : std::uint8_t {
    Method,
    Event,
    Property,
};

struct ParameterSpec {
    const char* name;            // nullptr for an unnamed object parameter
    const char* type;            // gecko type token, or "$TypeName" for a $ref
    const char* ref;             // referenced type name, or nullptr
    bool optional;
    std::int32_t minimum;        // sentinels when the schema states no bound
    std::int32_t maximum;
    const char* const* enumValues;  // nullptr unless the schema enumerates them
};

struct MemberSpec {
    const char* name;
    MemberKind kind;
    bool documented;   // MDN documents it, not merely the Gecko schema
    const ParameterSpec* parameters;
    int parameterCount;
    // A permission this member needs beyond its namespace's. Several namespaces
    // state permissions per member instead: tabs.hide needs tabHide and
    // tabs.captureTab needs <all_urls>, while plain tabs.* needs the tabs
    // permission. Empty means "whatever the namespace requires".
    const char* extraPermission;
};

struct NamespaceSpec {
    const char* name;
    // The permission the namespace requires. A "manifest:<key>" permission is
    // satisfied by declaring that manifest key rather than a permission string.
    const char* permission;
    ContextFlag contexts;
    int minManifestVersion;   // 2 when the schema states no lower bound
    int maxManifestVersion;   // 0 means unbounded
    const MemberSpec* members;
    int memberCount;
};

int namespaceCount();
int memberCount();

const NamespaceSpec* findNamespace(std::string_view name);
const MemberSpec* findMember(std::string_view namespaceName, std::string_view memberName);

} // namespace iridium::extensions::generated
"""

SOURCE_HEAD = BANNER + """
#include "extensions/generated/ApiCatalog.hpp"

#include <cstddef>
#include <cstring>
#include <string_view>

namespace iridium::extensions::generated {

namespace {

// The schemas write allowedContexts as a comma-separated list, e.g. "content,
// devtools".
//
// It is additive, not restrictive: it names the contexts a namespace reaches
// *besides* the extension's own. Read as a whitelist it would make
// storage.local, runtime and i18n unreachable from a background page, which
// contradicts the specification and would break most extensions on their first
// background call. So the base set is every extension-owned context, and the
// list adds content-script and devtools reach.
ContextFlag contextsFor(const char* allowed)
{
    std::uint32_t mask = ContextBackground | ContextExtensionPage;
    if (!allowed)
        return static_cast<ContextFlag>(mask);

    const char* it = allowed;
    while (*it) {
        const char* end = it;
        while (*end && *end != ',')
            ++end;
        std::string_view word(it, static_cast<std::size_t>(end - it));
        if (word == "content")
            mask |= ContextContentScript;
        else if (word == "devtools" || word == "devtools_only")
            mask |= ContextDevTools;
        it = (*end == ',') ? end + 1 : end;
    }
    return static_cast<ContextFlag>(mask);
}

"""

SOURCE_TAIL = """
} // namespace

const NamespaceSpec* findNamespace(std::string_view name)
{
    for (const NamespaceSpec& spec : kNamespaces) {
        if (name == spec.name)
            return &spec;
    }
    return nullptr;
}

const MemberSpec* findMember(std::string_view namespaceName, std::string_view memberName)
{
    const NamespaceSpec* space = findNamespace(namespaceName);
    if (!space)
        return nullptr;
    for (int i = 0; i < space->memberCount; ++i) {
        if (memberName == space->members[i].name)
            return &space->members[i];
    }
    return nullptr;
}

int namespaceCount()
{
    return static_cast<int>(std::size(kNamespaces));
}

int memberCount()
{
    int total = 0;
    for (const NamespaceSpec& spec : kNamespaces)
        total += spec.memberCount;
    return total;
}

} // namespace iridium::extensions::generated
"""


def cpp_string(value: str | None) -> str:
    if value is None:
        return "nullptr"
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def identifier(name: str) -> str:
    return "".join(c if c.isalnum() or c == "_" else "_" for c in name)


def cpp_enum_list(values: list[str], tables: list[str], symbol: str) -> str:
    """A named array for an enumerated parameter.

    A brace-enclosed list cannot initialise a `const char* const*` member
    directly, so the values go into their own array and the member names it.
    """
    if not values:
        return "nullptr"
    tables.append(f"const char* const {symbol}[] = {{\n"
                  + "".join(f"    {cpp_string(v)},\n" for v in values)
                  + "    nullptr,\n};\n")
    return symbol


def member_permission(spec: dict[str, Any], namespace_permission: str) -> str:
    """The permission a member needs beyond its namespace's, or empty.

    The schemas state permissions per member for several namespaces. A member
    that declares several needs all of them, so more than one is joined with a
    separator the dispatcher splits on; the common case is a single name.
    """
    permissions = [p for p in (spec.get("permissions") or []) if p != namespace_permission]
    return ",".join(permissions)


def parameter_rows(parameters: list[dict[str, Any]], tables: list[str],
                   value_prefix: str) -> list[str]:
    """Turn Gecko parameter specs into ParameterSpec initialisers.

    A parameter of type "function" is the callback the schema appends to an
    asynchronous method. The promise API does not take one, so it is not an
    argument to validate.
    """
    rows = []
    for param in parameters:
        if param.get("type") == "function":
            continue
        kind = param.get("type")
        if not kind and param.get("ref"):
            kind = f"${param['ref']}"
        rows.append(
            "    {{ {name}, {type}, {ref}, {optional}, {minimum}, {maximum}, {values} }},".format(
                name=cpp_string(param.get("name")),
                type=cpp_string(kind),
                ref=cpp_string(param.get("ref")),
                optional="true" if param.get("optional") else "false",
                minimum=param.get("minimum", -(2 ** 31)),
                maximum=param.get("maximum", 2 ** 31 - 1),
                values=cpp_enum_list(param.get("enum") or [], tables,
                                     f"{value_prefix}_{identifier(param.get('name') or 'anonymous')}"),
            )
        )
    return rows


def render(inventory: dict[str, Any]) -> dict[str, str]:
    exported = [ns for ns in inventory["namespaces"]
                if ns["namespace"] not in INTERNAL_NAMESPACES]

    tables: list[str] = []
    namespace_rows: list[str] = []

    for namespace in exported:
        name = namespace["namespace"]
        safe = identifier(name)
        permissions = namespace.get("permissions") or []
        api_permission = next((p for p in permissions if not p.startswith("manifest:")),
                              "")

        member_rows: list[str] = []
        members = [(member, spec) for member, spec in namespace["members"].items()
                   if spec.get("kind") in ("method", "event", "property")]
        for member_name, spec in sorted(members):
            rows = parameter_rows(spec.get("parameters") or [],
                              tables, f"kValues_{safe}_{identifier(member_name)}")
            if rows:
                symbol = f"kParameters_{safe}_{identifier(member_name)}"
                tables.append(f"const ParameterSpec {symbol}[] = {{\n"
                              + "\n".join(rows) + "\n};\n")
                parameters = f"{symbol}, {len(rows)}"
            else:
                parameters = "nullptr, 0"
            member_rows.append(
                "    {{ {name}, MemberKind::{kind}, {documented}, {parameters}, {extra} }},".format(
                    name=cpp_string(member_name),
                    kind={"method": "Method", "event": "Event",
                          "property": "Property"}[spec["kind"]],
                    documented="true" if spec.get("documented") else "false",
                    parameters=parameters,
                    extra=cpp_string(member_permission(spec, api_permission)),
                ))

        if member_rows:
            symbol = f"kMembers_{safe}"
            tables.append(f"const MemberSpec {symbol}[] = {{\n"
                          + "\n".join(member_rows) + "\n};\n")
            members_ref = f"{symbol}, {len(member_rows)}"
        else:
            members_ref = "nullptr, 0"

        contexts = ",".join(namespace.get("allowed_contexts") or [])
        namespace_rows.append(
            "    {{ {name}, {permission}, contextsFor({contexts}), {min}, {max}, {members} }},".format(
                name=cpp_string(name),
                permission=cpp_string(api_permission),
                contexts=cpp_string(contexts),
                min=namespace.get("min_manifest_version", 2),
                max=namespace.get("max_manifest_version", 0),
                members=members_ref,
            ))

    tables.append("const NamespaceSpec kNamespaces[] = {\n"
                  + "\n".join(namespace_rows) + "\n};\n")
    return {
        "ApiCatalog.hpp": HEADER,
        "ApiCatalog.cpp": SOURCE_HEAD + "\n".join(tables) + SOURCE_TAIL,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", default=str(DOCS / "data"))
    parser.add_argument("--out", default=str(GENERATED))
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed output is stale")
    args = parser.parse_args()

    inventory_path = Path(args.data) / "api-inventory.json"
    if not inventory_path.is_file():
        print(f"missing {inventory_path}; run tools/webext/inventory.py", file=sys.stderr)
        return 2
    with inventory_path.open(encoding="utf-8") as handle:
        inventory = json.load(handle)

    outputs = render(inventory)
    out = Path(args.out)
    stale = []
    for name, text in sorted(outputs.items()):
        path = out / name
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        if current == text:
            continue
        if args.check:
            stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"[webext] wrote {path.relative_to(ROOT)} "
              f"({len(text.splitlines())} lines)")

    if stale:
        print("generated API catalog is stale; run tools/webext/codegen.py:",
              file=sys.stderr)
        for path in stale:
            print(f"  - {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    if args.check:
        print("generated API catalog is current")
    return 0


if __name__ == "__main__":
    sys.exit(main())