#!/usr/bin/env python3
"""Generate the coverage documents from the compatibility database.

Two inputs, and only two:

  docs/extensions/compatibility.yaml  hand-written: what Iridium implements.
                                      This is the only place a status is stated.
  docs/extensions/data/*.json         generated by inventory.py: what the
                                      specification says exists.

Two outputs:

  docs/extensions/api-coverage.md
  docs/extensions/manifest-coverage.md

Keeping the hand-written status and the generated inventory separate is the
point. A status can never be quietly invented by the generator, and the
generator can never report an API as covered without the inventory saying it
exists in the first place.

The script fails when the database and the inventory disagree: an API the
inventory knows about but the database does not, a status from outside the
allowed set, a member listed as missing that the specification does not have,
or a `full` status with no test to back it. That is the mechanism that stops a
namespace from being marked complete merely because its JS namespace exists.

Usage:
    tools/webext/coverage.py [--check] [--data DIR] [--database FILE] [--out DIR]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover - developer tooling, reported clearly
    print("tools/webext/coverage.py needs PyYAML (python3 -m pip install pyyaml)",
          file=sys.stderr)
    raise SystemExit(2)

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs" / "extensions"

STATES = ("full", "partial", "experimental", "planned", "unsupported")
BROWSERS = ("firefox", "chrome", "safari")


class Report:
    """Collects problems so one run reports everything wrong, not just the first."""

    def __init__(self) -> None:
        self.errors: list[str] = []

    def error(self, message: str) -> None:
        self.errors.append(message)

    def require(self, condition: bool, message: str) -> bool:
        if not condition:
            self.error(message)
        return condition


def load_json(path: Path) -> Any:
    if not path.is_file():
        raise SystemExit(f"missing {path}; run tools/webext/inventory.py first")
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def support_cell(support: dict[str, Any] | None, browser: str) -> str:
    """Render one browser's support as a table cell.

    Takes the whole per-browser map and picks `browser` out of it, so a caller
    cannot accidentally pass the wrong scope and read every browser as
    unsupported.
    """
    if not support:
        return "-"
    entry = support.get(browser)
    if not isinstance(entry, dict):
        return "-"
    if entry.get("mirrors"):
        return "mirror"
    if not entry.get("supported"):
        return "no"
    version = entry.get("version_added")
    if version is True or version is None:
        cell = "-"
    elif version is False:
        cell = "no"
    else:
        cell = str(version)
    if entry.get("partial"):
        cell += "*"
    return cell


def status_badge(status: str) -> str:
    return {
        "full": "full",
        "partial": "partial",
        "experimental": "experimental",
        "planned": "planned",
        "unsupported": "unsupported",
    }[status]


def member_rows(namespace: dict[str, Any], entry: dict[str, Any]) -> list[str]:
    """One row per documented member, grouped by kind.

    A member that has documented sub-members (storage.local, tabs.create) also
    lists them, because that is where the interesting gaps live: storage.local
    exists but local.getBytesInUse does not.
    """
    rows: list[str] = []
    missing = set(entry.get("missing") or [])
    documented = {
        name: member
        for name, member in namespace["members"].items()
        if member.get("documented") and member.get("kind") != "type"
    }
    for kind, label in (("method", "Methods"), ("event", "Events"),
                        ("property", "Properties")):
        names = sorted(name for name, member in documented.items() if member["kind"] == kind)
        if not names:
            continue
        rows.append(f"| **{label}** | | | |")
        for name in names:
            support = documented[name].get("support") or {}
            # A sub-member can only be implemented when the member that owns it
            # is: storage.session.clear is not implemented merely because
            # storage.local.clear is.
            implemented = name not in missing
            rows.append(
                f"| `{name}` | {'yes' if implemented else 'no'} "
                f"| {support_cell(support, 'firefox')} "
                f"| {support_cell(support, 'chrome')} |"
            )
            sub = documented[name].get("members") or {}
            for sub_name in sorted(sub):
                sub_support = sub[sub_name].get("support") or {}
                path = f"{name}.{sub_name}"
                done = implemented and path not in missing
                rows.append(
                    f"| &nbsp;&nbsp;`{sub_name}` | {'yes' if done else 'no'} "
                    f"| {support_cell(sub_support, 'firefox')} "
                    f"| {support_cell(sub_support, 'chrome')} |"
                )
    return rows


def api_document(inventory: dict[str, Any], database: dict[str, Any], report: Report) -> str:
    statuses = database.get("api", {})
    meta = database.get("meta", {})
    lines: list[str] = []
    add = lines.append

    add("# API coverage")
    add("")
    add("Generated by `tools/webext/coverage.py` from "
        "`compatibility.yaml` (Iridium's status) and `data/api-inventory.json`")
    add("(the MDN and Gecko surface). Do not edit this file; edit the database.")
    add("")
    add("## How to read this")
    add("")
    add("A namespace is `full` only when its documented members, events, "
        "permissions,")
    add("errors and edge cases are implemented *and* covered by the named tests. "
        "A JS namespace")
    add("existing is not evidence of that. `partial` names what is missing in "
        "`compatibility.yaml`;")
    add("the member tables below list every documented member, so a missing one "
        "is visible next")
    add("to the implemented ones.")
    add("")
    add("The Firefox and Chrome columns are upstream support data from MDN's "
        "browser-compat-data,")
    add("kept so a divergence from Firefox has to be a decision rather than an "
        "accident. `*` marks")
    add("a partial upstream implementation. A `-` in the Chrome column for a "
        "Firefox-only API is")
    add("expected and is not a gap for Iridium.")
    add("")

    counts = inventory["_counts"]
    implemented = sum(1 for name in statuses.values() if name["status"] in
                      ("full", "partial", "experimental"))
    add(f"The specification surface is **{counts['namespaces']} namespaces** and "
        f"**{counts['members']} members**")
    add(f"({counts['by_kind'].get('method', 0)} methods, "
        f"{counts['by_kind'].get('event', 0)} events, "
        f"{counts['by_kind'].get('property', 0)} properties, "
        f"{counts['by_kind'].get('type', 0)} types).")
    add(f"{implemented} of them are at least partially implemented in Iridium "
        f"today.")
    add("")

    # Summary table first, so the state of the platform is one screen away.
    add("## Summary")
    add("")
    add("Members counts are top-level documented members: a nested member such "
        "as `storage.local.get`")
    add("is counted under its parent, and the per-namespace tables below show "
        "the nesting.")
    add("")
    add("| Namespace | Status | Members | Implemented | Firefox | Chrome | Notes |")
    add("| --- | --- | ---: | ---: | --- | --- | --- |")
    order = {state: index for index, state in enumerate(STATES)}
    by_name = {ns["namespace"]: ns for ns in inventory["namespaces"]}
    for name in sorted(statuses, key=lambda n: (order[statuses[n]["status"]], n)):
        entry = statuses[name]
        namespace = by_name.get(name)
        if namespace is None:
            report.error(f"api.{name}: not present in the upstream inventory")
            continue
        members = namespace["members"]
        callable_names = [member_name for member_name, member in members.items()
                          if member.get("documented") and member.get("kind") != "type"]
        missing = set(entry.get("missing") or [])
        # Count a top-level member as implemented unless the database says
        # otherwise; sub-members are counted separately so a namespace cannot
        # look complete on the strength of one working entry point.
        implemented_count = sum(1 for member_name in callable_names
                                if member_name not in missing)
        support = namespace.get("support") or {}
        note = (entry.get("notes") or entry.get("why") or "").strip().split("\n")[0]
        add(f"| [`{name}`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/"
            f"WebExtensions/API/{namespace.get('mdn_dir') or name}) "
            f"| {status_badge(entry['status'])} | {len(members)} "
            f"| {implemented_count}/{len(callable_names)} "
            f"| {support_cell(support, 'firefox')} | {support_cell(support, 'chrome')} "
            f"| {note} |")
    add("")

    unknown = sorted(set(by_name) - set(statuses))
    if unknown:
        add("### Namespaces with no status")
        add("")
        add("These exist in the specification but have no entry in "
            "`compatibility.yaml`. `coverage.py` fails on this, so the list is")
        add("empty in a passing build; it is printed here to show what was added.")
        add("")
        for name in unknown:
            add(f"- `{name}` ({len(by_name[name]['members'])} members)")
        add("")

    for name in sorted(statuses, key=lambda n: (order[statuses[n]["status"]], n)):
        entry = statuses[name]
        namespace = by_name.get(name)
        if namespace is None:
            continue
        add(f"## `{name}`")
        add("")
        add(f"**Status:** {status_badge(entry['status'])}")
        add("")
        if namespace.get("description"):
            add(f"{namespace['description']}")
            add("")
        if namespace.get("permissions"):
            add(f"**Permission:** `{', '.join(namespace['permissions'])}`")
            add("")
        if namespace.get("allowed_contexts"):
            add(f"**Allowed contexts:** `{', '.join(namespace['allowed_contexts'])}`")
            add("")
        if namespace.get("min_manifest_version") or namespace.get("max_manifest_version"):
            low = namespace.get("min_manifest_version", 2)
            high = namespace.get("max_manifest_version", "any")
            add(f"**Manifest version:** {low} to {high}")
            add("")
        if entry.get("why"):
            add(f"**Why unsupported:** {' '.join(entry['why'].split())}")
            add("")
        if entry.get("notes"):
            add(f"**Notes:** {' '.join(entry['notes'].split())}")
            add("")
        if entry.get("tests"):
            add(f"**Tests:** {', '.join(f'`{t}`' for t in entry['tests'])}")
            add("")
        rows = member_rows(namespace, entry)
        if rows:
            add("| Member | Implemented | Firefox | Chrome |")
            add("| --- | --- | --- | --- |")
            lines.extend(rows)
            add("")

    add("## Provenance")
    add("")
    sources = inventory.get("_sources") or {}
    if sources:
        add("| Source | Repository | Commit | License |")
        add("| --- | --- | --- | --- |")
        for key, spec in sorted(sources.items()):
            add(f"| {key} | `{spec.get('repo', '')}` | `{spec.get('ref', '')[:12]}` "
                f"| {spec.get('license', '')} |")
        add("")
    else:
        add("No provenance recorded: run `tools/webext/fetch.py` before "
            "`tools/webext/inventory.py`.")
        add("")
    return "\n".join(lines) + "\n"


def manifest_document(manifest_inventory: dict[str, Any], database: dict[str, Any],
                      report: Report) -> str:
    inventory = manifest_inventory
    statuses = database.get("manifest", {})
    lines: list[str] = []
    add = lines.append

    add("# Manifest coverage")
    add("")
    add("Generated by `tools/webext/coverage.py`; see `compatibility.yaml` for the "
        "statuses.")
    add("")
    add("`manifest_version` is 2 or 3. Keys are marked MV2-only, MV3-only or "
        "both by the")
    add("specification; a key that Iridium parses without acting on it is "
        "`partial`, because")
    add("parsing is not implementing.")
    add("")

    add("## Keys")
    add("")
    add("| Key | Status | Firefox | Chrome | MV | Notes |")
    add("| --- | --- | --- | --- | --- | --- |")
    order = {state: index for index, state in enumerate(STATES)}
    by_key = {key["key"]: key for key in inventory["keys"]}
    for name in sorted(statuses, key=lambda n: (order[statuses[n]["status"]], n)):
        entry = statuses[name]
        key = by_key.get(name)
        if key is None:
            report.error(f"manifest.{name}: not present in the upstream inventory")
            continue
        support = key.get("support") or {}
        mv = manifest_version_note(name)
        note = (entry.get("notes") or entry.get("why") or "").strip().split("\n")[0]
        add(f"| `{name}` | {status_badge(entry['status'])} "
            f"| {support_cell(support, 'firefox')} | {support_cell(support, 'chrome')} "
            f"| {mv} | {note} |")
    add("")

    unknown = sorted(set(by_key) - set(statuses))
    if unknown:
        add("### Keys with no status")
        add("")
        add("`coverage.py` fails when this list is non-empty.")
        add("")
        for name in unknown:
            add(f"- `{name}`")
        add("")

    missing = sorted(set(statuses) - set(by_key))
    if missing:
        add("### Entries with no specification")
        add("")
        for name in missing:
            add(f"- `{name}`")
        add("")

    add("## Permissions")
    add("")
    permissions = inventory.get("permissions", {})
    every = permissions.get("all", [])
    add(f"The specification defines **{len(every)}** permission identifiers. The "
        "classes below come from")
    add("the Gecko schema inheritance chain: a permission's class decides whether "
        "it may appear")
    add("in `permissions`, in `optional_permissions`, or in neither.")
    add("")
    for class_name, names in sorted((permissions.get("classes") or {}).items()):
        add(f"### `{class_name}` ({len(names)})")
        add("")
        add(", ".join(f"`{n}`" for n in names))
        add("")

    add("## Provenance")
    add("")
    sources = inventory.get("_sources") or {}
    if sources:
        add("| Source | Repository | Commit | License |")
        add("| --- | --- | --- | --- |")
        for key, spec in sorted(sources.items()):
            add(f"| {key} | `{spec.get('repo', '')}` | `{spec.get('ref', '')[:12]}` "
                f"| {spec.get('license', '')} |")
        add("")
    return "\n".join(lines) + "\n"


# MV2-only / MV3-only / MV2+3, from the specification's own annotations.
MV_NOTES = {
    "action": "MV3+",
    "background": "MV2+",
    "browser_action": "MV2",
    "host_permissions": "MV3+",
    "optional_host_permissions": "MV3+",
    "page_action": "MV2+",
    "user_scripts": "MV2",
}


def manifest_version_note(key: str) -> str:
    return MV_NOTES.get(key, "MV2+")


def member_paths(namespaces: list[dict[str, Any]], name: str) -> set[str]:
    """Every addressable member name of a namespace, including nested ones.

    A `missing:` entry may be `local.get` rather than `get`, because
    storage.local.get is a real member and its absence is a real gap. Only
    callable members are addressable; a field of a documented type is not a
    member the API layer implements.
    """
    paths: set[str] = set()
    for namespace in namespaces:
        if namespace.get("namespace") != name:
            continue
        for member_name, member in namespace["members"].items():
            if member.get("kind") != "type":
                paths.add(member_name)
            for sub_name, sub in (member.get("members") or {}).items():
                if sub.get("kind") in ("method", "property", "event"):
                    paths.add(f"{member_name}.{sub_name}")
    return paths


def ctest_names() -> set[str]:
    """Every test name CMake registers.

    A status that names a test which does not exist is a claim with nothing
    behind it, which is exactly what the status file is supposed to prevent, so
    the names are checked against CMakeLists.txt rather than trusted.
    """
    text = (ROOT / "CMakeLists.txt").read_text(encoding="utf-8")
    names = set(re.findall(r"add_test\(\s*NAME\s+(\S+)", text))
    # iridium_add_webview_test(<target> <test-name> <source> ...)
    names.update(re.findall(r"iridium_add_webview_test\(\s*\S+\s+(\S+)", text))
    return names


def validate(api_inventory: dict[str, Any], manifest_inventory: dict[str, Any],
             database: dict[str, Any], report: Report) -> None:
    """The checks that make the two documents trustworthy."""
    known_tests = ctest_names()
    unexpected = sorted(set(database) - {"meta", "api", "manifest"})
    report.require(not unexpected,
                   f"unexpected top-level keys in compatibility.yaml: {unexpected}")

    sections = (("api", api_inventory, "namespaces"), ("manifest", manifest_inventory, "keys"))
    for section, source, inventory_key in sections:
        statuses = database.get(section, {})
        report.require(bool(statuses),
                       f"compatibility.yaml has no '{section}' section")
        known = {entry["namespace"] if section == "api" else entry["key"]
                 for entry in source[inventory_key]}

        for name, entry in statuses.items():
            where = f"{section}.{name}"
            if not isinstance(entry, dict):
                report.error(f"{where}: entry must be a mapping")
                continue
            status = entry.get("status")
            if status not in STATES:
                report.error(f"{where}: status {status!r} is not one of {STATES}")
                continue
            if entry.get("tests") is None:
                report.error(f"{where}: 'tests' is required, even if empty")
            for test in entry.get("tests") or []:
                if test not in known_tests:
                    report.error(f"{where}.tests: '{test}' is not a CTest test "
                                 f"(no add_test(NAME {test}) in CMakeLists.txt)")
            if status == "full" and not entry.get("tests"):
                report.error(f"{where}: status 'full' requires at least one test")
            if status == "partial" and not (entry.get("missing") or entry.get("notes")
                                            or entry.get("why")):
                report.error(f"{where}: status 'partial' requires 'missing', "
                             "'notes' or 'why'")
            if status == "unsupported" and not entry.get("why"):
                report.error(f"{where}: status 'unsupported' requires 'why'")
            if status in ("full", "experimental") and entry.get("missing"):
                report.error(f"{where}: status {status!r} cannot list 'missing'")

            if section == "api" and name in known:
                members = member_paths(source[inventory_key], name)
                for gone in entry.get("missing") or []:
                    if gone not in members:
                        report.error(
                            f"{where}.missing: '{gone}' is not a member of "
                            f"'{name}' in the inventory (typo, or the member "
                            f"was renamed upstream)")

        for name in sorted(known - set(statuses)):
            report.error(f"{section}.{name}: in the upstream inventory but not "
                         f"in compatibility.yaml")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the documents are current instead of writing them")
    parser.add_argument("--data", default=str(DOCS / "data"))
    parser.add_argument("--database", default=str(DOCS / "compatibility.yaml"))
    parser.add_argument("--out", default=str(DOCS))
    args = parser.parse_args()

    data = Path(args.data)
    inventory = load_json(data / "api-inventory.json")
    manifest_inventory = load_json(data / "manifest-inventory.json")
    with Path(args.database).open(encoding="utf-8") as handle:
        database = yaml.safe_load(handle) or {}

    report = Report()
    validate(inventory, manifest_inventory, database, report)
    if report.errors:
        print("compatibility.yaml and the inventory disagree:", file=sys.stderr)
        for error in report.errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    outputs = {
        Path(args.out) / "api-coverage.md": api_document(inventory, database, report),
        Path(args.out) / "manifest-coverage.md": manifest_document(
            manifest_inventory, database, report),
    }

    if args.check:
        stale = []
        for path, text in outputs.items():
            current = path.read_text(encoding="utf-8") if path.is_file() else ""
            if current != text:
                stale.append(path)
        if stale:
            print("coverage documents are out of date; run tools/webext/coverage.py:",
                  file=sys.stderr)
            for path in stale:
                print(f"  - {path}", file=sys.stderr)
            return 1
        print("coverage documents are current")
        return 0

    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8")
        print(f"[webext] wrote {path.relative_to(ROOT)} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())